### ISSUE TITLE
NoNarrator 1.0.1 - Invalid Minecraft 1.20 Version

### ISSUE THREAD

**Issue by ghost** [545u/NoNarrator#1]
The latest mod release requests for Minecraft version 1.19.x

Here is the fabric error logs
`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'NoNarrator' (nonarrator) 1.0.1 with any version that is compatible with:
		 - minecraft 1.20
Unmet dependency listing:
	 - Mod 'NoNarrator' (nonarrator) 1.0.1 requires any 1.19.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.20!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

**Comment by IFedor-F** [comment]
Incorrect release on Modrinth, [here](https://github.com/545u/NoNarrator/releases/tag/1.0.1) is correct
[This release](https://modrinth.com/mod/nonarrator/version/1.0.1) is release for 1.19, and it can't load

**Comment by ItzSkyReed** [comment]
https://media.tenor.com/MdRHT4Alo7cAAAAM/%D0%B2%D1%88%D0%BE%D0%BA%D0%B5-%D1%8F%D0%B2%D1%88%D0%BE%D0%BA%D0%B5.gif

**Comment by 545u** [comment]
Oops, sorry. I fixed it. Thanks for letting me know!
